export const catalanCountryNames = {
  // Europa
  Spain: "Espanya",
  Ireland: "Irlanda",
  Poland: "Polònia",
  Romania: "Romania",
  Hungary: "Hongria",
  Ukraine: "Ucraïna",
  Germany: "Alemanya",
  "United Kingdom": "Regne Unit",
  Sweden: "Suècia",
  France: "França",
  Greece: "Grècia",
  Netherlands: "Països Baixos",
  Switzerland: "Suïssa",
  Finland: "Finlàndia",
  Belgium: "Bèlgica",
  Austria: "Àustria",
  Croatia: "Croàcia",
  Serbia: "Sèrbia",
  Bulgaria: "Bulgària",
  Moldova: "Moldàvia",
  Iceland: "Islàndia",
  Cyprus: "Xipre",
  Russia: "Rússia",
  Italy: "Itàlia",

  // Asia
  Turkey: "Turquia",
  Iraq: "Iraq",
  "Saudi Arabia": "Aràbia Saudita",
  Oman: "Oman",
  Yemen: "Iemen",
  Iran: "Iran",
  Afghanistan: "Afghanistan",
  Pakistan: "Pakistan",
  India: "Índia",
  Kazakhstan: "Kazakhstan",
  Bangladesh: "Bangladesh",
  Thailand: "Tailàndia",
  Malaysia: "Malàisia",
  Indonesia: "Indonèsia",
  Philippines: "Filipines",
  Mongolia: "Mongòlia",
  "South Korea": "Corea del Sud",
  "North Korea": "Corea del Nord",
  China: "Xina",
  Japan: "Japó",
  Cambodia: "Cambodja",

  // Oceania
  Australia: "Austràlia",
  "New Zealand": "Nova Zelanda",

  // America
  Canada: "Canadà",
  "United States": "Estats Units",
  Mexico: "Mèxic",
  Bolivia: "Bolívia",
  Chile: "Xile",
  Uruguay: "Uruguai",
  Ecuador: "Equador",
  Colombia: "Colòmbia",
  Venezuela: "Veneçuela",

  // West Africa
  Mauritania: "Mauritània",
  Nigeria: "Nigèria",
  "The Gambia": "Gàmbia",
  "Guinea-Bissau": "Guinea Bissau",
  Liberia: "Libèria",
  "Ivory Coast": "Costa d'Ivori",

  // North Africa
  Morocco: "Marroc",
  Algeria: "Algèria",
  Tunisia: "Tunísia",
  Libya: "Líbia",
  Egypt: "Egipte",
  Sudan: "Sudan",

  // East Africa
  "South Sudan": "Sudan del Sud",
  Ethiopia: "Etiòpia",
  Somalia: "Somàlia",
  Kenya: "Kenya",
  Tanzania: "Tanzània",

  // Central Africa
  Cameroon: "Camerun",
  Chad: "Txad",
  Gabon: "Gabon",

  // Southern Africa
  Zambia: "Zàmbia",
  Malawi: "Malawi",
  Mozambique: "Moçambic",
  Zimbabwe: "Zimbàbue",
  Namibia: "Namíbia",
  "South Africa": "Sud-àfrica",
};
